<?xml version="1.0" encoding="UTF-8" ?>
<results>
    <error file="Bibliotecas/Dominio_Tst/Apelido_Tst.hpp" line="18" id="noConstructor" severity="style" msg="The class &apos;ApelidoTst&apos; does not have a constructor although it has private member variables. Member variables of builtin types are left uninitialized when the class is instantiated. That may cause bugs or undefined behavior." />
    <error file="Bibliotecas/Dominio_Tst/Codigo_Tst.hpp" line="18" id="noConstructor" severity="style" msg="The class &apos;CodigoTst&apos; does not have a constructor although it has private member variables. Member variables of builtin types are left uninitialized when the class is instantiated. That may cause bugs or undefined behavior." />
    <error file="Bibliotecas/Dominio_Tst/Data_Tst.hpp" line="16" id="noConstructor" severity="style" msg="The class &apos;DataTst&apos; does not have a constructor although it has private member variables. Member variables of builtin types are left uninitialized when the class is instantiated. That may cause bugs or undefined behavior." />
    <error file="Bibliotecas/Dominio/Apelido.hpp" line="38" id="noExplicitConstructor" severity="style" msg="Class &apos;Apelido&apos; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided." />
    <error file="Bibliotecas/Dominio/Codigo.hpp" line="43" id="noExplicitConstructor" severity="style" msg="Class &apos;Codigo&apos; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided." />
    <error file="Bibliotecas/Dominio_Tst/Apelido_Tst.hpp" line="27" id="unusedPrivateFunction" severity="style" msg="Unused private function: &apos;ApelidoTst::validarCampo&apos;" />
    <error file="Fontes/Dominio_Tst/Apelido_Tst.cpp" line="42" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Apelido_Tst.cpp" line="45" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Apelido_Tst.cpp" line="56" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Apelido_Tst.cpp" line="57" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Bibliotecas/Dominio_Tst/Codigo_Tst.hpp" line="29" id="unusedPrivateFunction" severity="style" msg="Unused private function: &apos;CodigoTst::validarCampoOk&apos;" />
    <error file="Bibliotecas/Dominio_Tst/Codigo_Tst.hpp" line="30" id="unusedPrivateFunction" severity="style" msg="Unused private function: &apos;CodigoTst::validarCampoNOk&apos;" />
    <error file="Fontes/Dominio_Tst/Codigo_Tst.cpp" line="21" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Codigo_Tst.cpp" line="24" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Codigo_Tst.cpp" line="35" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Codigo_Tst.cpp" line="36" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Bibliotecas/Dominio_Tst/Data_Tst.hpp" line="27" id="unusedPrivateFunction" severity="style" msg="Unused private function: &apos;DataTst::validarCampoOk&apos;" />
    <error file="Bibliotecas/Dominio_Tst/Data_Tst.hpp" line="28" id="unusedPrivateFunction" severity="style" msg="Unused private function: &apos;DataTst::validarCampoNOk&apos;" />
    <error file="Fontes/Dominio_Tst/Data_Tst.cpp" line="32" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Data_Tst.cpp" line="35" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Data_Tst.cpp" line="46" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Dominio_Tst/Data_Tst.cpp" line="48" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="209" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="211" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="220" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="222" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="231" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="233" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="242" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="244" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="253" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="255" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="264" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="266" id="catchExceptionByValue" severity="style" msg="The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++." />
    <error file="Fontes/Utilidades/Manipulacao.cpp" line="66" id="unusedFunction" severity="style" msg="The function &apos;ePar&apos; is never used." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="288" id="unusedFunction" severity="style" msg="The function &apos;expect_NotNull&apos; is never used." />
    <error file="Fontes/Utilidades/TesteUnitario.cpp" line="284" id="unusedFunction" severity="style" msg="The function &apos;expect_Null&apos; is never used." />
    <error file="Fontes/Utilidades/Manipulacao.cpp" line="42" id="unusedFunction" severity="style" msg="The function &apos;haNum&apos; is never used." />
    <error file="Fontes/Utilidades/Manipulacao.cpp" line="10" id="unusedFunction" severity="style" msg="The function &apos;minuscula&apos; is never used." />
    <error id="missingIncludeSystem" severity="style" msg="Cppcheck cannot find all the include files. Cppcheck can check the code without the include files found. But the results will probably be more accurate if all the include files are found. Please check your project&apos;s include directories and add all of them as include directories for Cppcheck. To see what files Cppcheck cannot find use --check-config." />
</results>
